- build/gulpfile.vscode.web.js
- build/npm/postinstall.js
- extensions/shared.webpack.config.js
- extensions/typescript-language-features/web/src/serverHost.ts
Link T-650
Now that we're interacting with VSCode primarily as a submodule of `mnode` we need to update the `ts-plugin` reference to just be a sibling of `vscode`. I've also made a change to the build script and added a fix where the postinstall script was causing CI to fail due to some `git config` commands running in the submodule. 
_Note: My commits aren't verified here because I'm pushing them from mk1_
> Modifications required for CI

- extensions/shared.webpack.config.js
- src/tsconfig.json
- src/vs/code/browser/workbench/workbench.ts
- src/vs/workbench/api/browser/mainThreadTerminalService.membrane.ts
- src/vs/workbench/contrib/terminal/browser/terminal.contribution.membrane.ts
- src/vs/workbench/contrib/terminal/browser/terminalInstanceService.membrane.ts
- src/vs/workbench/contrib/terminal/browser/terminalProfileService.membrane.ts
- src/vs/workbench/contrib/terminal/browser/terminalService.membrane.ts
We don't want to show the `Terminal` tab since we don't support terminals in the Web IDE.
VSCode is very modular so most of the functionality comes in the form of "contributions", not only for extensions but also built-in features.
Many features in VSCode depend on terminal functionality (e.g. tasks) so it's not as easy as just deleting the contributions. I tried that and dependents start failing at runtime because there's no `ITerminalService`.
Thankfully VScode uses dependency injection everywhere, this allows us to replace components with dummy ones that don't do anything. so I replaced `TerminalService` with our own empty shell of a service. The empty shell is just there to satisfy the dependency injection system. Also did the same for a few other related services. 
I removed most of …
> Rip out terminals from VSCode

- src/vs/workbench/services/search/common/textSearchManager.ts
These changes simplify the search by using a single query.
- The original code performed searches across multiple folders (folderQueries). this PR simplifies this to search only in the root of the workspace
- By searching in only one folder instead of multiple, the search process will be faster and more efficient, especially when we have many membrane programs. 
https://github.com/membrane-io/mnode/pull/168
> Search only within the workspace/root folder.

- src/vs/code/browser/workbench/workbench.ts
- src/vs/workbench/browser/parts/editor/editorGroupWatermark.ts
- src/vs/workbench/browser/parts/titlebar/commandCenterControl.ts
- src/vs/workbench/browser/parts/titlebar/titlebarPart.ts
- Added a home link at the top-left corner
- Command center at the top doesn't show "workspace" anymore
- Removed the large letterpress logo when no file is open
- Remove the full-screen hotkey hint
> VSCode Customizations

- src/vs/workbench/api/browser/mainThreadFileSystemEventService.ts
https://github.com/microsoft/vscode/pull/207679/files
The latest upstream `microsoft/vscode` ignores this false alarm. Commenting it out in our fork for now, until we pull in the upstream.
==========
Close T-980
> T-980: Ignore false alarm file watcher error

- extensions/typescript-language-features/package.json
- extensions/typescript-language-features/src/configuration/configuration.ts
Defaults the TS server setting to suppress semantic errors for external packages to `false`. Here's an example:
Open the preview deployment on https://github.com/membrane-io/mnode/pull/217 and write some code with invalid types.
I am a bit confused by the status of this setting in vscode upstream. On the main branch [it is still `true`](https://github.com/microsoft/vscode/blame/main/extensions/typescript-language-features/package.json#L1447), but the latest git blame points to [this PR that flips it to `false`](https://github.com/microsoft/vscode/pull/212370).
> T-946: Do not suppress TS semantic diagnostics

- extensions/markdown-language-features/preview-src/index.ts
- extensions/markdown-language-features/src/preview/security.ts
- src/vs/workbench/contrib/webview/browser/pre/index.html
- src/vs/workbench/contrib/webview/browser/webviewElement.ts
- src/vs/workbench/contrib/webview/browser/webviewMessages.d.ts
The `index.html` file for extension WebViews gets fetched from a Microsoft CDN, and we're fetching a stale version that's missing the fix for markdown preview links. Instead of fixing that root CDN issue, which would be a bigger lift, this PR just updates the type of the href that the click handler expects.
See T-1173 description for more context.
> T-1173: Fix markdown preview links

- src/vs/workbench/browser/window.ts
- src/vs/workbench/contrib/url/browser/trustedDomains.ts
Related to https://github.com/membrane-io/mnode/pull/294
Also has the nice side effect of skipping the confirmation dialog for all links to membrane.io from the IDE (e.g. /share pages).
> T-1223: add `membrane.io` as a trusted domain

- extensions/typescript-language-features/package.json
We don't really need to have a separate tsserver instance for syntax highlighting because our programs are small. This should save some memory, speed up startup time, as well as make it less confusing to debug/develop our plugin since there will be only one instance per program.
> Disable typescript syntax server since we don't really need it

- extensions/typescript-language-features/src/tsServer/bufferSyncSupport.ts
- src/vs/editor/contrib/codelens/browser/codelensController.ts
While fixing a recent issue with ts-plugin I noticed that intellisense is actually slowed down to account for huge files and perhaps reduce flickering. I lowered a couple of delays and indeed feels much responsive, I think this should be okay because our files/projects tend to be small.
> Snappier intellisense

- src/vs/workbench/api/browser/viewsExtensionPoint.ts
- src/vs/workbench/contrib/files/browser/explorerViewlet.ts
- src/vs/workbench/contrib/files/browser/fileActions.contribution.ts
- src/vs/workbench/contrib/files/browser/fileActions.ts
- src/vs/workbench/contrib/files/browser/views/explorerView.ts
1. rm `EXPLORER` sidebar flash on login and signup
2. rm commands that open the file explorer*
1. rm `View: Show Explorer` command
2. rm `Files: Focus on Files Explorer` command
3. rm `Explorer: Focus on Folders View`
4. rm `Explorer: Focus on Open Editors View`
5. rm `Refresh Explorer`
6. rm `Collapse Folders in Explorer`
_*I left the file outline and timeline there for now_
https://github.com/user-attachments/assets/3051f902-9243-4fc4-8eb0-7706368638c7
https://github.com/user-attachments/assets/8fce27a9-123a-4fbd-9fbd-6f6d43d0376a
> T-1284: rm `EXPLORER` flash on load

- extensions/typescript-language-features/web/src/typingsInstaller/typingsInstaller.ts
To ignore this.
Uncaught (in promise) Error: unexpected response: [object Object]
at e.WebTypingsInstallerClient.handleResponse (tsserver.web.js:31:20991)
at Q.handleResponse (tsserver.web.js:31:20715)
at Q.sendResponse (tsserver.web.js:31:22537)
at Q.watchFiles (tsserver.web.js:7:2108512)
at Q.install (tsserver.web.js:7:2103298)
at tsserver.web.js:31:21551
> T-1153  Fix typings errors.

- src/vs/code/browser/workbench/workbench.ts
This command gets invoked when:
- The navigator loads its html
- When an error is shown (in case there's an error while loading)
> Add a workbench command to hide the splash screen

- extensions/typescript-language-features/src/commands/index.ts
- extensions/typescript-language-features/src/languageFeatures/rename.ts
Context: https://github.com/membrane-io/mnode/pull/397#discussion_r1900231491
> Add `typescript.provideRenameEdits` to integrate typescript renames into Membrane's `RenameProvider`

- src/vs/workbench/services/progress/browser/progressService.ts
We removed SCM from the activity bar, so I don't think we need the progress service to track it.
> Silence `Bad progress location: workbench.scm`

- src/vs/platform/actionWidget/browser/actionWidget.css
Now the quick fix action title text won't truncate, and we can see the full "Declare ... {type}"
Related: https://github.com/membrane-io/mnode/pull/412
> Remove action title text truncation

- src/vs/code/browser/workbench/workbench.ts
- src/vs/workbench/contrib/url/browser/trustedDomains.ts
See https://github.com/membrane-io/mnode/pull/485
1. Adds vscode command that emits an event for the tour
2. Configures membrane.io subdomains as trusted
> T-1342: add command to emit event for product tour

- src/vs/workbench/api/browser/viewsExtensionPoint.ts
- src/vs/workbench/browser/part.ts
- src/vs/workbench/browser/parts/auxiliarybar/auxiliaryBarPart.ts
- src/vs/workbench/browser/parts/editor/editorTabsControl.ts
- src/vs/workbench/browser/parts/editor/media/editorgroupview.css
- src/vs/workbench/browser/parts/editor/media/multieditortabscontrol.css
- src/vs/workbench/browser/parts/editor/multiEditorTabsControl.ts
- src/vs/workbench/browser/parts/media/compositepart.css
See: https://github.com/membrane-io/mnode/pull/506
- Reverted #49 so we can combine program overview and assistant in one gaze instance
- Made tabs a tad thinner so that our explorer buttons don't have to be so massive
BEFORE
AFTER
- Added this button to open aux bar
> Allow us to combine program overview and assistant. Thinner tabs

- extensions/package.json
- extensions/yarn.lock
See: https://github.com/membrane-io/mnode/pull/491
> Use `typescript` fork to get contextual typing of exports

- extensions/theme-defaults/themes/membrane_dark.json
> Remove stray red color for `*.async`

- src/vs/workbench/browser/parts/editor/editorCommands.ts
- src/vs/workbench/browser/parts/editor/editorGroupView.ts
- src/vs/workbench/browser/parts/editor/editorTabsControl.ts
- src/vs/workbench/browser/parts/editor/media/multieditortabscontrol.css
- src/vs/workbench/browser/parts/editor/multiEditorTabsControl.ts
1. Add custom `Dashboard` tab next to aux bar
2. Hide split view and triple dot menu icon buttons
3. Hide Dashboard default editor tab
4. Prevent closing the dashboard editor
> Add `Dashboard` button next to open aux bar button

- src/vs/workbench/browser/parts/editor/editorCommands.ts
- src/vs/workbench/browser/parts/editor/editorGroupView.ts
- src/vs/workbench/browser/parts/editor/editorTabsControl.ts
- src/vs/workbench/browser/parts/editor/media/multieditortabscontrol.css
- src/vs/workbench/browser/parts/editor/multiEditorTabsControl.ts
- src/vs/workbench/browser/parts/sidebar/sidebarPart.ts
- Reverts most of https://github.com/membrane-io/vscode/pull/61
- Bumps min width of sidebar
- Fixes split/grid view issues with aux bar toggle button
> Dashboard tab

- extensions/typescript-language-features/web/src/serverHost.ts
_Problem 2: I have a website program. I delete it and then create a new one again with new -> website, but it throws those errors. This happens because tsserver internally has a watcher that detects the creation of package.json, but within the TypeScript code, there is a return Debug.fail();._
Ignore package.json created events, removed on typescript@v5.5
https://github.com/microsoft/TypeScript/commit/f3f70df94e120bab69dd766bacd22089347b71c9
> Ignore package.json created events.

- src/vs/workbench/browser/parts/editor/editorGroupWatermark.ts
- src/vs/workbench/browser/parts/editor/editorTabsControl.ts
- src/vs/workbench/browser/parts/editor/media/editorgroupview.css
See https://github.com/membrane-io/mnode/pull/609
@juancampa, re your idea to show the editor tab bar when there are no open files:
- Editor tab bars are associated with editor groups
- There are settings to show single/multiple or hide tabs for editor groups
- But there isn’t an existing setting that would always show an editor tab bar
- It is possible for there to be editor groups with no editors (I've run into this when the dashboard is in a split view and I refresh the page)
- If we showed the editor tab bar for empty editors, we'd need to check position of each editor to conditionally render the tab bar or not, and there's already some logic that renders a close button (x icon) for an empty editor in split/grid view
- So I added the toggle button to the watermark instead
> Add aux bar toggle button to editor watermark

- src/vs/workbench/browser/parts/editor/editorTabsControl.ts
Fixes the 'AbstractContextKeyService has been disposed' errors (caused by not cleaning up event handlers).
cc @pmillspaugh
> Fix incorrect event cleanup (AbstractContextKeyService errors)
