membrane-io/vscode

src/vs/workbench/contrib/welcomeGettingStarted/browser/gettingStarted.contribution.ts

Don't open welcome page by default

---

build/lib/optimize.js
build/lib/optimize.ts

I still need to test if this loads correctly but at least the build contains the membrane files and not the old files.

Fix membrane overrides

---

src/vs/workbench/contrib/files/browser/fileActions.contribution.ts
src/vs/workbench/contrib/files/browser/fileCommands.ts
src/vs/workbench/contrib/files/browser/fileConstants.ts

Changes the minimum amount of vscode functionality to enable deleting programs

Add delete program logic

---

src/vs/workbench/contrib/files/browser/fileActions.contribution.ts
src/vs/workbench/contrib/files/browser/fileCommands.ts

No longer using some imports and that caused the build to fail. I'm commented them out.

Fix compile failures

---

build/gulpfile.vscode.web.js
src/vs/code/browser/workbench/workbench.ts

Dependency of https://github.com/membrane-io/mnode/pull/169

Add `version.json` to build

---

src/vs/code/browser/workbench/workbench.ts

Get the Membrane API token using the global authentication function.

---

src/vs/workbench/browser/parts/editor/editorGroupWatermark.ts
src/vs/workbench/browser/parts/titlebar/titlebarPart.ts
src/vs/workbench/workbench.common.main.ts
src/vs/workbench/workbench.web.main.ts

Comment out a bunch of contributions that we don't use like:
- Connecting to a remote vscode
- Telemetry (to MS)
- A survey system they sometimes use
- Normal vscode welcome screen

Remove unused features

---

src/vs/workbench/api/browser/viewsExtensionPoint.ts
src/vs/workbench/browser/parts/compositePart.ts

Companion PR to https://github.com/membrane-io/mnode/pull/205

T-919: Move Navigator to left sidebar (activity bar)

---

src/vs/workbench/browser/layout.ts

Related to https://github.com/membrane-io/mnode/pull/227

T-965 Reduce Logs panel default height

---

src/vs/code/browser/workbench/membrane.ts

We were accidentally using staging

Use correct api endpoint

---

src/vs/workbench/browser/layout.ts
src/vs/workbench/browser/media/part.css
src/vs/workbench/browser/part.ts
src/vs/workbench/browser/parts/auxiliarybar/auxiliaryBarPart.ts
src/vs/workbench/browser/parts/compositePart.ts
src/vs/workbench/browser/parts/editor/multiEditorTabsControl.ts
src/vs/workbench/browser/parts/media/compositepart.css
src/vs/workbench/browser/parts/paneCompositePart.ts
src/vs/workbench/browser/parts/panel/panelPart.ts
src/vs/workbench/browser/parts/sidebar/sidebarPart.ts
src/vs/workbench/browser/parts/titlebar/titlebarPart.ts
src/vs/workbench/contrib/files/browser/explorerViewlet.ts
src/vs/workbench/contrib/url/browser/trustedDomains.ts

See description of changes in https://github.com/membrane-io/mnode/pull/349

T-967 (ii): customize vscode

---

src/vs/code/browser/workbench/membrane.ts
src/vs/workbench/contrib/files/browser/fileConstants.ts

This is the command used when right clicking on a tab and selecting "Reveal in explorer view"

Use navigator instead of explorer when revealing files

---

src/vs/workbench/browser/parts/titlebar/media/titlebarpart.css
src/vs/workbench/browser/parts/titlebar/titlebarPart.ts

Only buggy on Safari 🤔. See https://github.com/membrane-io/mnode/pull/403

T-1290: fix safari M logo overlap

---

src/vs/base/browser/indexedDB.ts

Save keybindings

---

src/vs/workbench/browser/part.ts
src/vs/workbench/browser/parts/panel/panelPart.ts
src/vs/workbench/browser/parts/sidebar/sidebarPart.ts

https://github.com/user-attachments/assets/717c8525-f4fa-44c7-b4b8-f706f0d56aae

Fix ProgramOverview height

---

src/vs/workbench/browser/layout.ts
src/vs/workbench/contrib/webviewPanel/browser/webviewEditor.ts

Use zen-mode for dashboard. Improve zen-mode perf

---

extensions/theme-defaults/themes/membrane_dark.json
extensions/theme-defaults/themes/membrane_light.json
src/vs/workbench/services/themes/common/themeConfiguration.ts
src/vs/workbench/services/themes/common/workbenchThemeService.ts

See description in https://github.com/membrane-io/mnode/pull/464

T-1049: default color theme based on OS preference

---

extensions/theme-defaults/themes/membrane_dark.json
extensions/theme-defaults/themes/membrane_light.json

See https://github.com/membrane-io/mnode/pull/512

Tweak default themes

---

extensions/theme-defaults/themes/membrane_dark.json
extensions/theme-defaults/themes/membrane_light.json

Now the tags can be distinguished from the props.

Update theme to work correctly on .tsx files

---

src/vs/code/browser/workbench/workbench.ts
src/vs/workbench/browser/web.main.ts

See description of https://github.com/membrane-io/mnode/pull/533

T-1357: Listen for tour event to show package installer

---

src/vs/workbench/browser/parts/editor/multiEditorTabsControl.ts
src/vs/workbench/contrib/extensions/browser/extensionEditor.ts
src/vs/workbench/contrib/extensions/browser/extensionsList.ts
src/vs/workbench/contrib/preferences/browser/settingsLayout.ts
src/vs/workbench/contrib/url/browser/trustedDomains.ts

Opening a PR from @juancampa's branch so that we can merge it and point mnode back to `vscode/membrane-web`

Fix extensions not loading. Better tab titles

---

src/vs/workbench/contrib/extensions/browser/extensions.contribution.ts

cc https://github.com/membrane-io/mnode/pull/592#discussion_r2063984424
- before
- after

Disable extensions view and commands.

---

src/vs/workbench/contrib/extensions/browser/extensions.contribution.ts

```
TypeError: Cannot read properties of undefined (reading 'isWriteAccess')
at /Users/jhonny/temp/mnode/vscode/build/lib/nls.js:183:29
at /Users/jhonny/temp/mnode/vscode/node_modules/lazy.js/lazy.js:774:11
at recurseVisitor (/Users/jhonny/temp/mnode/vscode/node_modules/lazy.js/lazy.js:1794:14)
at /Users/jhonny/temp/mnode/vscode/node_modules/lazy.js/lazy.js:645:14
at /Users/jhonny/temp/mnode/vscode/node_modules/lazy.js/lazy.js:775:16
at recurseVisitor (/Users/jhonny/temp/mnode/vscode/node_modules/lazy.js/lazy.js:1794:14)
at forEach (/Users/jhonny/temp/mnode/vscode/node_modules/lazy.js/lazy.js:6157:11)
at recurseVisitor (/Users/jhonny/temp/mnode/vscode/node_modules/lazy.js/lazy.js:1787:16)
at /Users/jhonny/temp/mnode/vscode/node_modules/lazy.js/lazy.js:645:14
at …
```

Fix locale/nls import.

---

src/vs/code/browser/workbench/workbench.ts

Add sentry report issue command

---

extensions/theme-defaults/themes/membrane_dark.json
extensions/theme-defaults/themes/membrane_light.json

Before:
After:
*light mode is pretty much the same color it was before

Sash color change
